services:

  caddy:
    image: trailfox-caddy:staging
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile:ro
      - /var/www/trailfox.app:/var/www/trailfox.app:ro
      - ../client/assets/sprites:/var/www/trailfox.app/sprites:ro
      - caddy_data:/data
      - caddy_config:/config

  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: unless-stopped
    profiles:
      - tools
    env_file:
      - ./.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "127.0.0.1:${PGADMIN_PORT:-5050}:80"
    volumes:
      - trailfox_pgadmin_data:/var/lib/pgadmin

  grafana-alloy:
    image: grafana/alloy:latest
    restart: unless-stopped
    volumes:
      - ./alloy-config.river:/etc/alloy/config.river:ro
    command: run --server.http.listen-addr=0.0.0.0:12345 /etc/alloy/config.river
    ports:
      - "127.0.0.1:12345:12345"  # Optional UI
    depends_on:
      - postgis

volumes:
  trailfox_pg_data:
    name: trailfox_pg_data
    driver: local
  trailfox_pgadmin_data:
    name: trailfox_pgadmin_data
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
